### ISSUE TITLE
Performance: Numba vs Cython

### ISSUE THREAD

**Issue by franz101** [blakeaw/GAlibrate#4]
Great article you wrote about the project.
I was wondering about the speed.
There is also https://github.com/PytLab/gaft
Which uses mpi4py for multiprocessing...

Trying to understand what is the fastest solution in python....

**Comment by blakeaw** [comment]
@franz101 thanks!
I kind of forgot about going back to the performance analysis, but it is up now in [this notebook](https://github.com/blakeaw/galibrate_performance_comparison/blob/master/gao_implementation_scaling_comparison.ipynb). Thanks for reminding me. 

I wasn't familiar with gaft, but I took a brief look and I went ahead and did a quick rough comparison for one model which is up in [this notebook](https://github.com/blakeaw/galibrate_performance_comparison/blob/master/galibrate_vs_gaft_3point_line_fit.ipynb). I only ran the serial version of gaft against the galibrate-numba implementation, but for the case I tested galibrate was roughly 30x faster. However, I should note that it looks like gaft has more GA features, particularly the choice of crossover operators. And I didn't try comparison against the mpi4py version of gaft.

**Comment by franz101** [comment]
Wow amazing work! Indeed performance can be greatly improved. I was trying to get an overview of current packages to work with as deap has some performance issues in my opinion.
Also research in genetic algorithms has been stagnating since fancy neural networks came.

I'm currently working on a virtual ant colony with economic features just out of curiosity. It's inspired by this video: https://www.youtube.com/watch?v=r_It_X7v-1E

Are you using GA to simulate ecosystems?

**Comment by blakeaw** [comment]
@franz101, 
Thanks. 
No, I put together GAlibrate thinking it could use a GA to estimate unknown model parameters for systems biology models through optimization-based fitting to experimental data. However, it was really more of learning project for myself more than anything else. I've kind of had a latent fascination with genetic algorithms for several years, but I'm certainly not an expert in the subject.
